import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "raw-forest-honey",
    name: "Raw Forest Honey",
    nameNp: "कच्चो वन मह",
    price: 28,
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600",
    category: "honey",
    badge: "bestseller",
    rating: 4.9,
    reviews: 186,
    description: "Cold-pressed nectar from deep woodland flowers. Rich, dark, and complex with earthy undertones.",
    flavorNotes: ["Dark Berry", "Oak", "Earth"],
    pairings: ["Blue Cheese", "Dark Bread", "Whiskey"],
    weight: "250g",
    calories: 60,
    totalFat: "0g",
    sugars: "17g",
    sodium: "0mg",
  },
  {
    id: "wildflower-blossom",
    name: "Wildflower Blossom Honey",
    nameNp: "जंगली फूलको मह",
    price: 24,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600",
    category: "honey",
    badge: "new",
    rating: 4.9,
    reviews: 128,
    description: "A multi-floral blend with notes of lavender, clover, and a hint of wild thyme. Harvested from high-altitude meadows.",
    flavorNotes: ["Lavender", "Clover", "Thyme"],
    pairings: ["Soft Cheese", "Herbal Tea", "Sourdough"],
    weight: "250g",
    calories: 60,
    totalFat: "0g",
    sugars: "17g",
    sodium: "0mg",
  },
  {
    id: "ginger-infused",
    name: "Ginger Infused Honey",
    nameNp: "अदुवा मिश्रित मह",
    price: 32,
    image: "https://images.unsplash.com/photo-1612540139150-4c44b3dc4b3d?w=600",
    category: "honey",
    badge: undefined,
    rating: 4.7,
    reviews: 94,
    description: "Spicy, warming cold perfect for winter tea rituals. Organic ginger steeped in pure wildflower honey.",
    flavorNotes: ["Ginger", "Spice", "Floral"],
    pairings: ["Lemon Tea", "Stir Fry", "Yogurt"],
    weight: "250g",
    calories: 65,
    totalFat: "0g",
    sugars: "18g",
    sodium: "0mg",
  },
  {
    id: "ceylon-cinnamon",
    name: "Ceylon Cinnamon Honey",
    nameNp: "सिलोन दालचिनी मह",
    price: 30,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600",
    category: "honey",
    badge: "bestseller",
    rating: 4.8,
    reviews: 142,
    description: "Smooth texture paired with premium organic Ceylon Cinnamon. A warming, aromatic experience.",
    flavorNotes: ["Cinnamon", "Warm Spice", "Caramel"],
    pairings: ["Oatmeal", "Apple", "Hot Milk"],
    weight: "250g",
    calories: 62,
    totalFat: "0g",
    sugars: "17g",
    sodium: "0mg",
  },
  {
    id: "golden-bee-pollen",
    name: "Golden Bee Pollen",
    nameNp: "सुनौलो मौरी पराग",
    price: 32,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    category: "hive-gifts",
    badge: "bestseller",
    rating: 4.8,
    reviews: 76,
    description: "Vibrant golden granules perfect for topping yogurt or smoothies. Rich in vitamins, minerals, and protein.",
    weight: "150g",
    calories: 90,
    totalFat: "2g",
    sugars: "10g",
    sodium: "5mg",
  },
  {
    id: "artisan-beeswax-candles",
    name: "Artisan Beeswax Candles",
    nameNp: "हस्तकला मैनबत्ती",
    price: 18,
    image: "https://images.unsplash.com/photo-1602607644278-73e94697d09a?w=600",
    category: "hive-gifts",
    badge: "handmade",
    rating: 4.9,
    reviews: 203,
    description: "Pure triple-filtered wax for artisanal candles and natural skin balms. Set of 2 with natural scent.",
    weight: "Set of 2",
  },
  {
    id: "fresh-honeycomb",
    name: "Fresh Honeycomb",
    nameNp: "ताजा मौरीको चाका",
    price: 38,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600",
    category: "hive-gifts",
    badge: undefined,
    rating: 4.9,
    reviews: 58,
    description: "The purest way to consume honey — straight from the dedicated hive cells to your table.",
    weight: "Single Frame",
    calories: 70,
    totalFat: "0g",
    sugars: "18g",
    sodium: "0mg",
  },
  {
    id: "royal-jelly",
    name: "Royal Jelly",
    nameNp: "रोयल जेली",
    price: 45,
    image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=600",
    category: "hive-gifts",
    badge: undefined,
    rating: 4.7,
    reviews: 44,
    description: "The Superfood of queens — packed with essential amino acids and complete B vitamins for vitality.",
    weight: "100g",
    calories: 55,
    totalFat: "1g",
    sugars: "12g",
    sodium: "2mg",
  },
];

export const getProductById = (id: string): Product | undefined =>
  products.find((p) => p.id === id);

export const getHoneyProducts = (): Product[] =>
  products.filter((p) => p.category === "honey");

export const getHiveGifts = (): Product[] =>
  products.filter((p) => p.category === "hive-gifts");
